name: AlararsHardcore
display-name: "Alarar's Hardcore"
version: ${version}
main: com.mineplayers.alararshardcore.AlararsHardcore
api-version: "1.21"
folia-supported: true
commands:
  mount:
    description: Summon your seasonal mount
    aliases: [caballo]
  ahcdebug:
    description: Debug command for Alarar's Hardcore
    permission: alararsHardcore.admin
